### ISSUE TITLE
Not working with Angular 2 RC4

### ISSUE THREAD

**Issue by Sebschock** [ksachdeva/angular2-progressbar#1]
Hi, 

I get an error when trying to use your script with RC4:

`ORIGINAL EXCEPTION: No Directive annotation found on LineProgressComponent`

Any idea how to get it to work with rc4? (I'm using your example from https://github.com/ksachdeva/angular2-progressbar)

/Sebastian

**Comment by ksachdeva** [comment]
Hi Sebastian,

I tried the example and it was working for me. However the dependencies were set to rc5 so I have set them rc4 now. May be this will help ! There were also typings related warning that are now fixed.

Could you please try again the example. Make sure to pull the latest example repository.

Regards
Kapil

**Comment by ksachdeva** [comment]
upgraded to angular 2 final release and can not reproduce your issue. closing it for now. open again if you see the problem.
